#!/bin/bash
#
# Usage: ./export-id3c-metadata <sfs-sample-barcodes.csv>
#
# Export ID3C metdata for given sample barcodes provided in <sfs-sample-barcodes.csv>
# The provded CSV should have two columns: `nwgc_id` and `sfs_sample_barcode`
# Results are printed as a CSV to stdout. You'll likely want to redirect output
# to a new file.
#
#
set -euo pipefail

if [ -z ${1+x} ]; then
    echo "A positional <sfs-sample-barcodes.csv> is required."
    exit 1
fi

columns=$(head -n1 $1)
expected_columns="nwgc_id,sfs_sample_barcode"
if [ "$columns" != "$expected_columns" ]; then
    echo "Error: CSV columns do not match expected columns «"$expected_columns"»." >&2
    exit
fi

psql --quiet --no-align --tuples-only --set ON_ERROR_STOP= <<<"
    create temp table batch(nwgc_id text, sfs_sample_barcode citext);
    \copy batch ("$columns") from '"$1"' csv header

    create temp view batch_export as (
        select
            nwgc_id,
            shipping.genome_submission_metadata_v1.*
        from batch
        left join shipping.genome_submission_metadata_v1 using (sfs_sample_barcode)
        order by nwgc_id
    );

    \copy (select * from batch_export) to pstdout with csv header
"
